### ISSUE TITLE
Ability to know when a ModifyRigidBodyVelocity FollowModifier is exceeding a given distance from the object it's following

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/VRTK.Unity.Core#115]
Requires #22

Currently the ModifyRigidBodyVelocity FollowModifier has no way of knowing if the source Transform is too far away from the target Transform.

This is important when using it for a grab mechanic as if the two transforms become too separated you want to automatically drop the object.

My suggestion is a public distance field on the ModifyRigidBodyVelocity component when when the UpdatePosition process happens it checks to see at the end of the process whether the distance between the source and the target has been exceeded.

If they have been exceeded then it should emit an event (just a `float, object` Unity event of `distance, sender`)

This event can then be hooked into to know if the distance has exceeded and call whatever action is required to end the grab state.

It can also be useful for when teleporting. You could have the OnTeleporting event turn off the logic that causes the distance to do the drop (otherwise you'd drop things on teleporting)

**Comment by bddckr** [comment]
I wonder if this should be part of the superclass and therefore implemented in all subclasses. I could have the same need for the teleporting example, even when I use the transform changing modifier.
