### ISSUE TITLE
VelocityEstimator works with local space

### ISSUE THREAD

**Issue by bddckr** [ExtendRealityLtd/VRTK.Unity.Core#119]
The `VelocityEstimator` currently only works with local transform data, which is not useful in a lot of cases, especially in case of a user structuring their scripts via the game object hierarchy.

The suggested fix is to switch to global values.

---

Additionally we should discuss changing the SDK repos' `VelocityEstimator`s to be called `ControllerVelocityEstimator` as they are not generically usable, only the `Core` repo one is.

**Comment by thestonefox** [comment]
Related PRs

https://github.com/ExtendRealityLtd/VRTK.Unity.OculusUtilities/pull/16
https://github.com/ExtendRealityLtd/VRTK.Unity.SteamVR/pull/15
