### ISSUE TITLE
CameraColorOverlay never resets the material color

### ISSUE THREAD

**Issue by bddckr** [ExtendRealityLtd/VRTK.Unity.Core#152]
We should probably just save the material's color in `OnEnable`, then restore to that value in `OnDisable`.

An alternative solution is to ensure to only work on a _copy_ of the material, but that gives the additional burden of allowing to access that copy and respond to the user changing the original material "prefab".

**Comment by thestonefox** [comment]
I think i fixed this with https://github.com/ExtendRealityLtd/VRTK.Unity.Core/commit/dc97f66bc0a3211951d9588686461fe84d94d0a2
