### ISSUE TITLE
Ability to accurately move a set of colliders to track another GameObject

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/VRTK.Unity.Core#16]
This will enable the ability of tracking what the VR tracked objects are colliding with (e.g. the controllers).

**Comment by thestonefox** [comment]
I think we've proven this can be done with the Object Follow script right?

**Comment by thestonefox** [comment]
What about if the Collision Tracker has public methods that can digest Collision Tracker events, then you can just chain Collision Trackers together

so you'd put collision tracker on your oculus controllers and your vive controllers and then just wire their events up to a common Collision Tracker, which is basically just re-emitting the event

**Comment by bddckr** [comment]
Great idea!

I think one would always want to forward **all** events, not just specific ones. That means we could flip it around and make the CollisionTracker have a list of CollisionTrackers that it subscribes to OnEnable and unsubscribes in OnDisable, just forwarding any incoming event by emitting it's own one.

**Comment by bddckr** [comment]
The generic EventForwarder I built should be able to solve this particular use case of "alias collision forwarding".
