### ISSUE TITLE
Some usages of the ? operator are wrong

### ISSUE THREAD

**Issue by bddckr** [ExtendRealityLtd/VRTK.Unity.Core#175]
We can't use that operator for Unity objects as Unity's override of the equality for null checks forces us to do direct null checks instead

**Comment by thestonefox** [comment]
Anything that is of type GameObject Transform or extends MonoBehaviour can't use the ? operator for null checking

**Comment by bddckr** [comment]
It's actually way more than that: Anything inheriting from `UnityEngine.Object`.

**Comment by bddckr** [comment]
I'll review and test with ReSharper soon as it can list those all!
