### ISSUE TITLE
Allow the PlayAreaRepresentation to be offset based on where the headset is within the PlayArea

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/VRTK.Unity.Core#206]
At the moment the PlayAreaRepresentation can scale an object to the size of the current play area but it does not offset that object based on where the headset is within the play area.

**Comment by thestonefox** [comment]
So i think for this to work, the simplest solution is a new component that takes a `source` and an `offset` (e.g. PlayArea + Headset) and is iProcessable and in the `Process` method does `diff = source.position - offset.position` if the diffed value has changed then it emits an event of `PositionOffsetChanged(diff)` this diff Vector3 can then be passed to the `PositionProperty.DoSetProperty(Vector3)` to move the representation into the appropriate offset position.

Questions: 

* Should this offset calculator component only work on transform position, or should the single component calculate the offset between two transforms position, rotation, scale and emit events for each. Or should there be a TransformPositionOffsetCalculator (plus one for Rotation and one for Scale).
* What namespace should this sit in? It's no a mutator, it's purely a calculation (or an operation). Should we move `Mutation` namespace into `Data/Mutation` and then have another namespace of `Data/Operation` and this could perhaps then sit under `Data/Operation/TransformProperty/OffsetCalculator` (or PositionOffsetCalculator, etc).

**Comment by bddckr** [comment]
* One for each property to keep implementation simple and prevent wasting cycles when just one operation is needed. We already do this with modifiers IIRC.
* Mutations are operations I'd say so we want something like `Data/Type/TransformProperty/Position/Operation(/Mutation)`. Mutation being optional here as I wonder if the distinction between them and operations in general are needed. We should strive to keep the namespace hierarchy flat.

**Comment by thestonefox** [comment]
Linking in with https://github.com/ExtendRealityLtd/VRTK.Unity.Core/issues/212

So we're saying potentially we have

`Data/Type/Transform/Position/` as the namespace
then have
 * `PositionMutator`
 * `OffsetCalculator`

problem now is obviously the `Mutator` and the `OffsetCalculator` all share a bunch of logic so will all probably be based of an abstract class so where would these abstract classes go?

**Comment by bddckr** [comment]
Into that same namespace. We don't need to have abstract classes far away from the subclasses, nor do we want it to I think!

**Comment by thestonefox** [comment]
so you'd have

`Data/Type/Transform/Mutator.cs`
and then
`Data/Type/Transform/Position/PositionMutator.cs`
?

**Comment by bddckr** [comment]
👍

**Comment by thestonefox** [comment]
The Offset stuff would be:

`Data/Type/Transform/OffsetCalculator.cs`

and then

`Data/Type/Transform/Position/OffsetCalculator.cs`

(`PositionMutator` can just be `Position/Mutator.cs`)

**Comment by bddckr** [comment]
Well that will leave us with multiple `Mutator`s, won't it? So right now in the editor I will type in `Mutator` and either get a list of all of them with no way to differentiate them or a single one, depending on how Unity handles it.

**Comment by thestonefox** [comment]
That's true.

But then we're in a position where we repeat the namespace in the class name.

I'm also unsure of the best place for all this stuff

we already have `Data/Type/Transformation` namespace which allows us to convert from one type to another type (e.g. bool -> float)

`Transformations` are I guess not an Operation on a single type. so could we have

`Data/Type/Operation/`
-> `Data/Type/Operation/TransformMutator.cs` (base for transform property mutations)
-> `Data/Type/Operation/TransformPositionMutator.cs`

Although this feels silly as the mutator now only mutates each property type of the data type.

In reality we're only looking to operate on Transforms...

so instead should this not sit within `Data/Type` at all?

And maybe be `Data/Operation/Transform`

and within there we have

`Data/Operation/Transform/PropertyMutator.cs` (base)
`Data/Operation/Transform/PositionPropertyMutator.cs`
...

`Data/Operation/Transform/OffsetCalculator.cs` (base)
`Data/Operation/Transform/PositionOffsetCalculator.cs`
...

**Comment by thestonefox** [comment]
so this reads as 

`mutate the property "position" of a transform through the data operation`

or

`calculate the offset of positions on a transform`

This is where it doesn't work for me.

The first one is acting on a single transform. the second one is relying on two transforms.

**Comment by thestonefox** [comment]
`Data/Type/Transformation` is about transforming between `type A` and `type B` so I think it works being inside `Data/Type/Transformation`.

`Mutation` is mutating an existing DataType data. but in the case of Transform we don't want to mutate all of it's properties in one class so we split them. We want a way of updating the Transform position/rotation/scale independently.

So in this regard, is Transform not a normal DataType like another class? Transform is a form of data though, but offset calculations are not working on a single data type.

I just keep feeling that `Data/Type` isn't the right namespace for this stuff.

But also `TransformMutation` and `TransformOffsetCalculation` do live in the same world (or namespace hierarchy)

**Comment by thestonefox** [comment]
Maybe we can drop a namespace and just have

`Data/Operation/Transform/PropertyMutator.cs`
`Data/Operation/Transform/OffsetCalculator.cs`

These are now types of Operation on Transform Data

**Comment by thestonefox** [comment]
Or drop another and be

`Data/Operation/TransformPropertyMutator.cs`
`Data/Operation/TransformPositionPropertyMutator.cs`
`Data/Operation/TransformOffsetCalculator.cs`
`Data/Operation/TransformPositionOffsetCalculator.cs`

**Comment by thestonefox** [comment]
blocks #212
