### ISSUE TITLE
Move namespace `Mutation` to `Data/Type/Mutation`

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/VRTK.Unity.Core#212]
https://github.com/ExtendRealityLtd/VRTK.Unity.Core/tree/master/Scripts/Mutation

I also suggest renaming `TransformProperty` to `Transform` so it would go

`Data/Type/Mutation/Transform`

then `Property` is the base class of transform mutations

The other idea would be to do `Data/Type/Transform/Mutation`

then anything to do with the datatype transform are kept together
so you'd have `Data/Type/Transform/Mutation/Property.cs` and for the offset calculators they would go in `Data/Type/Transform/Operation/OffsetCalculator.cs`

**Comment by bddckr** [comment]
I prefer per-type namespaces as the grouping of Transform to Transform things makes more sense to me than just having a list of types next to each other and another list of mutations of those.

I think we also should be looking into naming these better. "Property" isn't restricted to a Transform at all, so if we can find something to make that more obvious (just TransformProperty?) I'd love that!

**Comment by thestonefox** [comment]
are you saying you prefer `Data/Type/Transform/Mutation`?

**Comment by bddckr** [comment]
Yes, sorry.

**Comment by bddckr** [comment]
I suppose we will not be moving them all into a folder/namespace in case it's just a single thing, so we may have a hard time finding names for the other various types...

**Comment by thestonefox** [comment]
Well in that regards.

isn't the `Data/Type/Transform/Mutation/Property.cs` be a good name?

I want to mutate property of the data type Transform?

You'd have `Property.cs` as the base then: `PositionProperty.cs` `RotationProperty.cs` `ScaleProperty.cs`

**Comment by bddckr** [comment]
Ah yeah that sounds better, but it still means I can't just type in "Transform" into the AddComponent dialog. Which is fine... Perhaps we just create another ticket to discuss having `[AddComponentMenu]` attributes that makes this easier, though I dislike changing the name that way as folks will have a harder time looking up docs and or the .cs file.

**Comment by thestonefox** [comment]
As we agreed on #206

#########
Data/Type/Transform/Mutator.cs
and then
Data/Type/Transform/Position/PositionMutator.cs
#########

**Comment by thestonefox** [comment]
`Data/Type/Transform/Position/Mutator.cs`

**Comment by thestonefox** [comment]
```
Data/Operation/TransformPropertyMutator.cs
Data/Operation/TransformPositionMutator.cs
```

**Comment by thestonefox** [comment]
requires #206
