### ISSUE TITLE
Mutators' axis lock is reversed

### ISSUE THREAD

**Issue by bddckr** [ExtendRealityLtd/VRTK.Unity.Core#238]
As a user I expect the checkboxes to represent what the mutator will modify, but currently the axis locks are exactly that - locks. Therefore the checkboxes have an inversed meaning and a check actually means it will **not** be used.

**Comment by thestonefox** [comment]
So anywhere there is a axis bool field (whatever we have called it)

instead of saying "lock these axes" i.e. put a tick box in the axis you want to lock.

we'll state "affected axes" and you put a tick box in every axis you want to affect i.e. any unticked box will be a locked axis.
