### ISSUE TITLE
Replace all instances of `for` index counters from being single letter variables

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/VRTK.Unity.Core#254]
We have an inconsistency of some `for` loops using `int i` and others using `int index`

it's our preference to never use abbreviations to avoid confusion, so any instance of `int i` should be replaced with `int index` or renaming `index` to a more appropriate name e.g. `int clipIndex`

**Comment by bddckr** [comment]
(That more appropriate name should only be used if more than one index is used. There is no need to create longer identifier names when there is no possible confusion about it.)
