### ISSUE TITLE
Ability to emit a signal when a controller input is received

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/VRTK.Unity.Core#9]
The concept of signals will basically be events with extra controls to allow for things like controller input.

e.g. button press, axis changes

These will be agnostic for each SDK and will simply emit an event when a (controller) input is detected. Other scripts will then digest these signals to determine another course of action to occur.

This will decouple the input mechanisms to other scripts (such as turning on or off a pointer).

**Comment by thestonefox** [comment]
probably just needs to be a collection of abstract UnityEvents that can be extended by the controller SDK in question

so

Button press <bool>
Button touch <bool>
1d axis change <float>
2d axis change <vector2>
3d axis change <vector3>

Then some additional scripts that can massage the data and re-emit such as

accept 2 * 1d events and re-emit a 2d axis event

**Comment by bddckr** [comment]
>probably just needs to be a collection of abstract UnityEvents that can be extended by the controller SDK in question

If we let the SDK repos provide components that emit (void, bool, float, Vector3) events there is no need to have a "controller SDK" at all probably. Additionally nothing of this need to live in the Core repo as nothing cares for this:
- SDK specific component emits something
- Core component has method that takes that something
- Inspector + code allows to wire these up
