### ISSUE TITLE
Don't state types in XML docs

### ISSUE THREAD

**Issue by bddckr** [ExtendRealityLtd/VRTK.Unity.Core#91]
We need to make sure to not repeat types all the time in the XML docs:
```c#
/// <param name="initiator">The <see cref="object"/> which initiated the method.</param>
```
can just be
```c#
/// <param name="initiator">The initiator of this method.</param>
```
Additionally we should probably note this in `CONTRIBUTING.md`.

**Comment by thestonefox** [comment]
Whenever we come across this issue in the code, we should make a note of the offending file and line so we can batch up the fixes into a single commit

**Comment by thestonefox** [comment]
I think we're aware of this now and we'll just fix as we go. Propose closing this
