### ISSUE TITLE
Change TransformData to use global scale instead of local scale

### ISSUE THREAD

**Issue by bddckr** [ExtendRealityLtd/VRTK.Unity.Core#92]
With #86 there exists an extension method on `Transform` to set the scale of a transform in world scale, i.e. global scale.

Since all the other properties and fields in `TransformData` use global space except for the scale we should change the scale to use that, too.

This change needs to be done carefully to prevent this from breaking any functionality.

**Comment by thestonefox** [comment]
Completed with https://github.com/ExtendRealityLtd/VRTK.Unity.Core/commit/65e8af9b681f9af6a6e62a3a6b203bb8fa0f4d40
